spring.application.name=SpringbootBlogApp

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringCrud
spring.datasource.username=postgres
spring.datasource.password=haris
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true